server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: default

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.batch_size: 20
        criteria.literal_handling_mode: BIND

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sklbx?currentSchema=be
    username: postgres
    password: 1234
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 7190000
      minimumIdle: 2
      maximumPoolSize: 50
